bigquerylogging: email, secret_key are required
Error: 400 - Bad Request:

    Title:  Bad request
    Detail: missing required user (email in ux)

Error: 400 - Bad Request:

    Title:  Bad request
    Detail: missing required secret_key